# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "14fa5dd8e7343a710c4198be96d225df"
name = "Pc builder"
handle = "pc-builder-4"
application_url = "https://animals-newport-ntsc-immediately.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://animals-newport-ntsc-immediately.trycloudflare.com/auth/callback", "https://animals-newport-ntsc-immediately.trycloudflare.com/auth/shopify/callback", "https://animals-newport-ntsc-immediately.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
